apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: task-api-pdb
  namespace: task-management
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: task-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mysql-pdb
  namespace: task-management
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: mysql
