spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskdb_dev
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com.taskapi: DEBUG
    org.springframework.web: DEBUG
