apiVersion: v1
kind: Secret
metadata:
  name: task-api-secret
  namespace: task-management
type: Opaque
data:
  # Base64 encoded values
  mysql-username: dGFza3VzZXI=  # taskuser
  mysql-password: dGFza3Bhc3M=  # taskpass
  mysql-root-password: cm9vdHBhc3M=  # rootpass
  mysql-database: dGFza2Ri  # taskdb
