apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
      - name: locust
        image: locustio/locust
        ports:
        - containerPort: 8089
        command: ["locust"]
        args: ["--master", "--host=http://task-frontend-service"]
        volumeMounts:
        - name: locust-scripts
          mountPath: /mnt/locust
      volumes:
      - name: locust-scripts
        configMap:
          name: locust-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: locust-service
spec:
  selector:
    app: locust-master
  ports:
    - port: 8089
      targetPort: 8089
  type: LoadBalancer
