apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  namespace: monitoring
  labels:
    app: locust
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
      role: master
  template:
    metadata:
      labels:
        app: locust
        role: master
    spec:
      containers:
      - name: locust
        image: locustio/locust:latest
        ports:
        - containerPort: 8089
        - containerPort: 5557
        env:
        - name: LOCUST_MODE
          value: "master"
        - name: TARGET_HOST
          value: "http://task-management-service.task-management.svc.cluster.local"
        volumeMounts:
        - name: locust-scripts
          mountPath: /mnt/locust
        command: ["locust"]
        args: ["--master", "-f", "/mnt/locust/locustfile.py"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: locust-scripts
        configMap:
          name: locust-scripts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  namespace: monitoring
  labels:
    app: locust
    role: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: locust
      role: worker
  template:
    metadata:
      labels:
        app: locust
        role: worker
    spec:
      containers:
      - name: locust
        image: locustio/locust:latest
        env:
        - name: LOCUST_MODE
          value: "worker"
        - name: LOCUST_MASTER
          value: "locust-master-service"
        - name: TARGET_HOST
          value: "http://task-management-service.task-management.svc.cluster.local"
        volumeMounts:
        - name: locust-scripts
          mountPath: /mnt/locust
        command: ["locust"]
        args: ["--worker", "--master-host=locust-master-service", "-f", "/mnt/locust/locustfile.py"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: locust-scripts
        configMap:
          name: locust-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: locust-master-service
  namespace: monitoring
spec:
  selector:
    app: locust
    role: master
  ports:
  - name: web
    port: 8089
    targetPort: 8089
  - name: master
    port: 5557
    targetPort: 5557
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: locust-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: locust.taskmanagement.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: locust-master-service
            port:
              number: 8089
