apiVersion: v1
kind: Service
metadata:
  name: task-management-service
  namespace: task-management-dev
  labels:
    app: task-management-api
    environment: dev
spec:
  selector:
    app: task-management-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
