apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-management

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml

commonLabels:
  environment: production
  managed-by: argocd

images:
  - name: task-management-api
    newName: 123456789012.dkr.ecr.us-east-1.amazonaws.com/task-management-api
    newTag: latest
