version: '3.8'

services:
  task-api:
    image: task-management-api:${VERSION:-latest}
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: >-
        -Xmx1g
        -Xms512m
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=200
        -Dspring.profiles.active=prod
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_root_password
      - mysql_password
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

secrets:
  mysql_root_password:
    external: true
  mysql_password:
    external: true
